[Variables]
; HDD letters
HDD1=C:
HDD2=D:
HDD3=E:
HDD4=R:
HDD5=Z:

; Show top processes? (impacts CPU usage)
SHOW_TOP_PROCESSES=1

; Ignored processes
IgnoreProcesses=_Total|Idle|System|Memory Compression|Registry|system|dwm|explorer|csrss|lsass|svchost|spoolsv|wmpnetwk
;|ShellExperienceHost|SearchUI|WinStore.App|HxOutlook|SystemSettings|LockApp|YourPhone|WindowsInternal.ComposableShell.Experiences.TextInput.InputApp|MicrosoftEdge|NahimicSvc32|Microsoft.Photos

; Ping address
PING_ADDRESS=1.1.1.1

; Afterburner path
AFTERBURNER_EXE="C:\Program Files (x86)\MSI Afterburner\MSIAfterburner.exe"
RTSS_EXE="C:\Program Files (x86)\RivaTuner Statistics Server\RTSS.exe"

;; Styling
; Global
FontName=Segoe UI
FontColor=255,255,255,220
FontEffectColor=255,255,255,75
SolidColor=0,0,0,66
LineColor=255,255,255,125
LineColor2=255,255,255,255
BarColor=255,255,255,133
BarColorBack=50,50,50,100
FontEffectColorInv=0,0,0,255

; Date & Time specific colors
FontColor_Time=255,255,255,220
FontColor_Month=255,255,255,210
FontColor_Day=255,255,255,200

;; Translations
CPU_Name=AwesomeCPU
GPU_Name=AwesomeGPU
Temperature=Temperature
Memory=Memory
FPS=FPS
none=–
Network=Network
Download=Download
Upload=Upload
Read=Read
Write=Write
Ping=Ping
HDDs=Drives
RecycleBin=Recycle Bin
RecycleBin_Empty="empty, "

;; Tooltips
Tooltip_OpenDrive=Open drive
Tooltip_OpenTaskManager=Open task manager
Tooltip_OpenAfterburner=Open MSI Afterburner
Tooltip_OpenRTSS=Open RivaTuner Statistics Server
Tooltip_OpenThisPC=Open This PC
Tooltip_OpenNetworkAndSharing=Open Network and sharing center
Tooltip_OpenOrEmptyRecycleBin=Open/Empty Recycle Bin

;; Pi-hole addon
Pihole_Address=http://pi.hole
Pihole_UpdateRate=60
Pihole_AdsBlocked=Blocked
Pihole_DNSQueries=Queries
Pihole_Clients=clients
Tooltip_OpenPihole=Open Pi-hole
