[Variables]
; HDD letters
HDD1=C:
HDD2=D:
HDD3=E:
HDD4=R:
HDD5=Z:

; Show top processes? (impacts CPU usage)
SHOW_TOP_PROCESSES=1

; Ignored processes
IgnoreProcesses=_Total|Idle|System|Memory Compression|Registry|system|dwm|explorer|csrss|lsass|svchost|spoolsv|wmpnetwk
;|ShellExperienceHost|SearchUI|WinStore.App|HxOutlook|SystemSettings|LockApp|YourPhone|WindowsInternal.ComposableShell.Experiences.TextInput.InputApp|MicrosoftEdge|NahimicSvc32|Microsoft.Photos

;; Styling
; Global
FontName=Segoe UI
FontColor=255,255,255,220
FontEffectColor=255,255,255,75
SolidColor=0,0,0,66
LineColor=255,255,255,125
BarColor=255,255,255,133
BarColorBack=50,50,50,100
FontEffectColorInv=0,0,0,255

; Date & Time specific colors
FontColor_Time=255,255,255,220
FontColor_Month=255,255,255,210
FontColor_Day=255,255,255,200

;; Translations
CPU_Name=AwesomeCPU
GPU_Name=AwesomeGPU
Temperature=Temperature
Memory=Memory
FPS=FPS
none=–
Network=Network
Download=Download
Upload=Upload
HDDs=Drives
Tooltip_Open=Open
